language: go

go:
 - 1.12.x
 - 1.11.x
 - 1.10.x
 - master

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

notifications:
 email: false

before_install:
 - go get -t -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
