language: go

go:
 - 1.12.x
 - 1.11.x
 - 1.10.x
 - master

script:
 - go test -v ./...

notifications:
 email: false

before_install:
 - go get github.com/kshedden/dstream/dstream
 - go get github.com/kshedden/dstream/formula

